name: Render R Markdown

on:
  push:
    paths:
      - "**.md"
  workflow_dispatch:

jobs:
  render:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install system dependencies
        run: |
          sudo apt-get update

      - name: Install R packages
        run: |
          Rscript -e 'install.packages(c("rmarkdown", "knitr", "tinytex"))'
          Rscript -e 'tinytex::install_tinytex()'

      - name: Render R Markdown
        run: |
          Rscript -e 'rmarkdown::render("paper.md", output_format = rmarkdown::pdf_document(keep_tex = TRUE))'

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: rendered-pdf-and-tex
          path: |
            paper.pdf
            paper.tex

      - name: Commit PDF to repository
          uses: EndBug/add-and-commit@v9
          with:
            message: '(auto) Paper Tex Draft'
            # This should be the path to the .tex file within your repo.
            add: 'paper.tex'
